apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresql-server
  name: postgresql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: postgresql-server
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: tests
            - name: POSTGRES_PASSWORD
              value: prisma
            - name: POSTGRES_USER
              value: prisma
          image: postgres:latest
          name: postgresql-server
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
