apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: profile-service
  name: profile-service
spec:
  ports:
    - name: "3006"
      port: 3006
      targetPort: 3006
  selector:
    io.kompose.service: profile-service
status:
  loadBalancer: {}
